apiVersion: v1
kind: Service
metadata:
  labels:
    app: nyt-today
  name: nyt-today
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: nyt-today
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nyt-today
  name: nyt-today
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nyt-today
  template:
    metadata:
      labels:
        app: nyt-today
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: nyt-today
          image: acrogenesis/nyt-today:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        - name: tunnel
          image: cloudflare/cloudflared:2020.12.0
          imagePullPolicy: Always
          command: ["cloudflared", "tunnel"]
          args:
            - --url=http://127.0.0.1:8080
            - --hostname=nyt-today.acrogenesis.com
            - --origincert=/etc/cloudflared/cert.pem
            - --no-autoupdate
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: tunnel-secret
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: tunnel-secret
          secret:
            secretName: acrogenesis.com
      terminationGracePeriodSeconds: 0
